/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfacegrafica;

import javax.swing.JOptionPane;
import java.util.Iterator;
import classededados.Professor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import fabrica.FabricaOrdenacao;
import static fabrica.FabricaOrdenacao.getOrdenacao;
import persistencia.ProfessorPersistenciaTemplateMethod;
import persistencia.OrdenarPorNome;
import persistencia.OrdenarPorMatricula;
import persistencia.OrdenarPorEscola;
import persistencia.OrdenarPorTitulacao;
        
/**
 *
 * @author denner
 */
public class Janela extends javax.swing.JFrame {
    
        
        
    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGridProfessores = new javax.swing.JTable();
        RADIO_ORDENAR_MATRICULA = new javax.swing.JRadioButton();
        RADIO_ORDENAR_NOME = new javax.swing.JRadioButton();
        RADIO_ORDENAR_ESCOLA_E_NOME = new javax.swing.JRadioButton();
        RADIO_ORDENAR_TITULACAO_E_MATRICULA = new javax.swing.JRadioButton();
        RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOME = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LISTA DE ALUNOS");

        jTableGridProfessores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricula", "Nome", "Escola", "Titulacão"
            }
        ));
        jScrollPane1.setViewportView(jTableGridProfessores);

        RADIO_ORDENAR_MATRICULA.setText("ORDENAR POR MATRICULA");
        RADIO_ORDENAR_MATRICULA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADIO_ORDENAR_MATRICULAActionPerformed(evt);
            }
        });

        RADIO_ORDENAR_NOME.setText("ORDENAR POR NOME");
        RADIO_ORDENAR_NOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADIO_ORDENAR_NOMEActionPerformed(evt);
            }
        });

        RADIO_ORDENAR_ESCOLA_E_NOME.setText("ESCOLA E NOME");
        RADIO_ORDENAR_ESCOLA_E_NOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADIO_ORDENAR_ESCOLA_E_NOMEActionPerformed(evt);
            }
        });

        RADIO_ORDENAR_TITULACAO_E_MATRICULA.setText("TITULACAO E MATRICULA");
        RADIO_ORDENAR_TITULACAO_E_MATRICULA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADIO_ORDENAR_TITULACAO_E_MATRICULAActionPerformed(evt);
            }
        });

        RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOME.setText("ESCOLA, TITULACAO E NOME");
        RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOMEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(RADIO_ORDENAR_MATRICULA)
                .addGap(18, 18, 18)
                .addComponent(RADIO_ORDENAR_NOME)
                .addGap(42, 42, 42)
                .addComponent(RADIO_ORDENAR_ESCOLA_E_NOME)
                .addGap(34, 34, 34)
                .addComponent(RADIO_ORDENAR_TITULACAO_E_MATRICULA)
                .addGap(18, 18, 18)
                .addComponent(RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOME)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RADIO_ORDENAR_MATRICULA)
                    .addComponent(RADIO_ORDENAR_NOME)
                    .addComponent(RADIO_ORDENAR_ESCOLA_E_NOME)
                    .addComponent(RADIO_ORDENAR_TITULACAO_E_MATRICULA)
                    .addComponent(RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOME))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void imprimirNaGrid(ArrayList<Professor> dados){
        try{
            DefaultTableModel model =  (DefaultTableModel) jTableGridProfessores.getModel();
            model.setNumRows(0);
            int pos = 0;
            
                while(pos < dados.size()){
                String[] linha = new String[4];
                Professor obj = dados.get(pos);
                linha[0]= obj.getMatricula();
                linha[1]= obj.getNome();
                linha[2]= obj.getEscola();
                linha[3]= obj.getTitulacao();
                model.addRow(linha);
                pos++;
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }
                
    
     private void imprimirNaGridTeste(ArrayList<Professor> dados){
        try{
            DefaultTableModel model =  (DefaultTableModel) jTableGridProfessores.getModel();
            model.setNumRows(0);
            int pos = 0;
            
                while(pos < dados.size()){
                String[] linha = new String[4];
                Professor obj = dados.get(pos);
                linha[0]= obj.getMatricula();
                linha[1]= obj.getNome();
                linha[2]= obj.getEscola();
                linha[3]= obj.getTitulacao();
                model.addRow(linha);
                pos++;
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }
    
    
    private void RADIO_ORDENAR_ESCOLA_E_NOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADIO_ORDENAR_ESCOLA_E_NOMEActionPerformed
        // TODO add your handling code here:
         try{
           imprimirNaGrid(getOrdenacao("ESCOLA_E_NOME").listagemDeProfessores());
           
            
            RADIO_ORDENAR_MATRICULA.setSelected(false);
           RADIO_ORDENAR_NOME.setSelected(false);
           RADIO_ORDENAR_TITULACAO_E_MATRICULA.setSelected(false);
           RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOME.setSelected(false);
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
        
    }//GEN-LAST:event_RADIO_ORDENAR_ESCOLA_E_NOMEActionPerformed

    private void RADIO_ORDENAR_MATRICULAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADIO_ORDENAR_MATRICULAActionPerformed
        // TODO add your handling code here:
         try{
            //String matricula = "./src/dados/ArquivoAlunos_28_33_120_csv.csv";
            //OrdenadoPorMatricula objeto = new OrdenadoPorMatricula(matricula);
            imprimirNaGrid(getOrdenacao("MATRICULA").listagemDeProfessores());
           RADIO_ORDENAR_NOME.setSelected(false);
           RADIO_ORDENAR_ESCOLA_E_NOME.setSelected(false);
           RADIO_ORDENAR_TITULACAO_E_MATRICULA.setSelected(false);
           RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOME.setSelected(false);
         }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_RADIO_ORDENAR_MATRICULAActionPerformed

    private void RADIO_ORDENAR_NOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADIO_ORDENAR_NOMEActionPerformed
        // TODO add your handling code here:
         try{
            //String matricula = "./src/dados/ArquivoAlunos_28_33_120_csv.csv";
            //OrdenadoPorMatricula objeto = new OrdenadoPorMatricula(matricula);
            imprimirNaGrid(getOrdenacao("NOME").listagemDeProfessores());
           RADIO_ORDENAR_MATRICULA.setSelected(false);
           RADIO_ORDENAR_ESCOLA_E_NOME.setSelected(false);
           RADIO_ORDENAR_TITULACAO_E_MATRICULA.setSelected(false);
           RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOME.setSelected(false);
         }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_RADIO_ORDENAR_NOMEActionPerformed

    private void RADIO_ORDENAR_TITULACAO_E_MATRICULAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADIO_ORDENAR_TITULACAO_E_MATRICULAActionPerformed
        // TODO add your handling code here:
             try{
          imprimirNaGrid(getOrdenacao("TITULACAO_E_MATRICULA").listagemDeProfessores());
          
           RADIO_ORDENAR_MATRICULA.setSelected(false);
           RADIO_ORDENAR_NOME.setSelected(false);
           RADIO_ORDENAR_ESCOLA_E_NOME.setSelected(false);
           RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOME.setSelected(false);
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }


    }//GEN-LAST:event_RADIO_ORDENAR_TITULACAO_E_MATRICULAActionPerformed

    private void RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOMEActionPerformed
        // TODO add your handling code here:
         try{
           imprimirNaGrid(getOrdenacao("ESCOLA_TITULACAO_NOME").listagemDeProfessores());
           RADIO_ORDENAR_MATRICULA.setSelected(false);
           RADIO_ORDENAR_NOME.setSelected(false);
           RADIO_ORDENAR_ESCOLA_E_NOME.setSelected(false);
           RADIO_ORDENAR_TITULACAO_E_MATRICULA.setSelected(false);
           
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RADIO_ORDENAR_ESCOLA_E_NOME;
    private javax.swing.JRadioButton RADIO_ORDENAR_ESCOLA_E_TITULACOA_E_NOME;
    private javax.swing.JRadioButton RADIO_ORDENAR_MATRICULA;
    private javax.swing.JRadioButton RADIO_ORDENAR_NOME;
    private javax.swing.JRadioButton RADIO_ORDENAR_TITULACAO_E_MATRICULA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGridProfessores;
    // End of variables declaration//GEN-END:variables
}
